---
# 删除指定文件 ...
delfile:
  - /var/del/ddd
# 删除指定文件到包中，如果有重复文件，则自动覆盖替换 ...
addfile:
  "/var/del/ddd": "/var/add/ddd"
# 全局替换 ...
replaces:
  - old: "dedecms"
    new: "DedeCMS"
  - old: "DedeBIZ"
    new: "DedeCMS"
# 全局根据Go模版替换内容 ...
parse:
  d: sss
  f: ssss
# 输出转码格式
charset:
  - UTF-8
  - GBK
# 需要转化的文件后缀 ...
suffix: [php, htm, html, txt, js, css, inc, xml, md]
